CREATE TABLE IF NOT EXISTS shoes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  archived INTEGER NOT NULL DEFAULT 0,
  createdAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mileages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shoesId INTEGER NOT NULL,
  miles REAL NOT NULL,
  createdAt TEXT NOT NULL,
  FOREIGN KEY (shoesId) REFERENCES shoes(id) ON DELETE CASCADE
);
